<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>LiteDB.Studio</RootNamespace>
    <AssemblyName>LiteDB.Studio</AssemblyName>
    <ApplicationIcon>LiteDB.Studio.ico</ApplicationIcon>
    <LangVersion>latest</LangVersion>
    <Platforms>AnyCPU</Platforms>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <NoWarn>$(NoWarn);WFO1000;CA1416</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DefineConstants>TRACE</DefineConstants>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LiteDB\LiteDB\LiteDB.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="App.config" CopyToOutputDirectory="PreserveNewest" />
    <None Include="packages.config" />
    <None Include="ILMerge.props" />
    <None Include="ILMergeOrder.txt" />
    <None Include="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\**\*.*" CopyToOutputDirectory="PreserveNewest" />
    <EmbeddedResource Include="ICSharpCode.TextEditor\Resources\**\*.*" />
  </ItemGroup>

</Project>